# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administor/Desktop/DigitalDesign/Washer/Washer.cache/wt [current_project]
set_property parent.project_path C:/Users/Administor/Desktop/DigitalDesign/Washer/Washer.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Administor/Desktop/DigitalDesign/Washer/Washer.srcs/sources_1/new/Divider.v
  C:/Users/Administor/Desktop/DigitalDesign/Washer/Washer.srcs/sources_1/new/seg_decoder.v
  C:/Users/Administor/Desktop/DigitalDesign/Washer/Washer.srcs/sources_1/new/data_select.v
  C:/Users/Administor/Desktop/DigitalDesign/Washer/Washer.srcs/sources_1/new/bling.v
  C:/Users/Administor/Desktop/DigitalDesign/Washer/Washer.srcs/sources_1/new/time_dec.v
  C:/Users/Administor/Desktop/DigitalDesign/Washer/Washer.srcs/sources_1/new/choose_mode.v
  C:/Users/Administor/Desktop/DigitalDesign/Washer/Washer.srcs/sources_1/new/seg_7_led.v
  C:/Users/Administor/Desktop/DigitalDesign/Washer/Washer.srcs/sources_1/new/light_ctrl.v
  C:/Users/Administor/Desktop/DigitalDesign/Washer/Washer.srcs/sources_1/new/button_signal.v
  C:/Users/Administor/Desktop/DigitalDesign/Washer/Washer.srcs/sources_1/new/FSM.v
  C:/Users/Administor/Desktop/DigitalDesign/Washer/Washer.srcs/sources_1/new/Washer.v
}
read_xdc C:/Users/Administor/Desktop/DigitalDesign/Washer/Washer.srcs/constrs_1/new/CSTR.xdc
set_property used_in_implementation false [get_files C:/Users/Administor/Desktop/DigitalDesign/Washer/Washer.srcs/constrs_1/new/CSTR.xdc]

synth_design -top Washer -part xc7a100tcsg324-1
write_checkpoint -noxdef Washer.dcp
catch { report_utilization -file Washer_utilization_synth.rpt -pb Washer_utilization_synth.pb }
